"""
OpenAI Handler
Handles all the connections between OpenAI and this software. Careful! This takes money to run!
"""
import openai
import logging


def getText(prompt, max_tokens, temp, model, secret, loglevel):
    """
    This function is used to get text from OpenAI's API.
    :param prompt: The prompt to give to the AI.
    :param max_tokens: The maximum number of tokens to consume
    :param temp: The temperature of the AI
    :param model: The model to use
    :param secret: The API key to use
    :param loglevel: The log level to use
    :return: The text generated by the AI
    """
    logging.basicConfig(level=loglevel)
    openai.api_key = secret
    logging.debug("Getting text from OpenAI...")
    response = openai.Completion.create(model=model, prompt=prompt, temperature=temp,
                                        max_tokens=max_tokens)
    logging.debug("Got text from OpenAI! " + response.choices[0].text.strip())
    return response.choices[0].text.strip().replace("\n", " ")
